### ISSUE TITLE
pants

### ISSUE THREAD

**Issue by jgarte** [russell/pygments-cl-repl#2]
Hi,

I'm curious to know why pants was chosen to be used in the context of this project.

**Comment by russell** [comment]
jgart ***@***.***> writes:

> I'm curious to know why pants was chosen to be used in the context of
> this project.

Mostly because i'm responsible for developer productivity in my day job
and i was experimenting with this repository.

One thing that is true, is that the implementation of Pants has been
more invasive than i would like.  If you are considering packaging this
for Guix, I can remove all dependencies on Pants, it's not needed.  But
i might keep it around as a fancy test interface.  I'll just revert it's
control over the setup.py, which is probably it's biggest compatability
issue.

Are there specific issues that you found while trying to use pants is
this package?

**Comment by russell** [comment]
pants is no longer a requirement to build this project please submit any further questions to the mailing list https://lists.sr.ht/~rsl/sphinxcontrib-cldomain
